### Obtener todas las notas
GET http://localhost:3000/notes

### Obtener nota por id
GET http://localhost:3000/notes/2

### Obtener categorias de nota por id
GET http://localhost:3000/notes/2/categories
### Obtener nota por categorias
GET http://localhost:3000/notes?category=Chores

### Obtener notas no/archivadas
GET http://localhost:3000/notes?archived=true

### Crear una nota
POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "Compras de supermercado",
    "content": "Leche, huevos, pan",
    "archived": false,
    "categories": ["Chores", "Shallow Work"]
}
### Crear una nota
POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "Curso fullstack",
    "content": "stack MERN",
    "archived": true,
    "categories": ["Learning", "Shallow Work"]
}

### Archivar/Desarchivar una nota
PATCH http://localhost:3000/notes/archive/1

 
### Actualizar una nota
PATCH http://localhost:3000/notes/1
Content-Type: application/json

{
    "title": "MAIAMEEEEEE"
}

### Borrar una nota
DELETE http://localhost:3000/notes/1



###################################CATEGORIAS###################

### Obtener todas las Categorias
GET http://localhost:3000/category

### Obtener Categoria por id
GET http://localhost:3000/category/1


### Crear Categorias
POST http://localhost:3000/category
Content-Type: application/json

{
    "name": "Learning"
}
### Crear Categorias
POST http://localhost:3000/category
Content-Type: application/json

{
    "name": "Chores"
}
### Crear Categorias
POST http://localhost:3000/category
Content-Type: application/json

{
    "name": "Body care"
}


### Borrar una Categoria
DELETE http://localhost:3000/category/1


